services:
  mcserver:
    image: mcserver:latest
    container_name: mcserver
    environment:
      - Xmx=4G
      - Xms=1G
      - SERVER_NAME=server.jar
      - USE_OWN_SERVER=false
    stdin_open: true # 打开标准输入

    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - ./app:/app